eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

server:
  port: 800

test:
  eve: ahahhahhhahahah

spring:
  application:
    name: zuulServer


zuul:
  routes:
    service-api-listener: /zuul-api-listener/**
    custom-service-name1:
      path: /zuul-api-driver/**
      url: http://localhost:8881
    custom-service-name2:
      path: /a-foward/**
      url: forward:/myController

  #指定请求头中的哪些字段是敏感的，敏感字段是不会向网关后面的微服务传播的，如果为空表示所有请求头都透传到后面微服务。
  sensitive-headers: token
#  prefix: /api
  strip-prefix: true #实际访问时是否移除前缀

service-api-listener:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# Actuator
management:
  endpoint:
    routes:
      enabled: true
    health:
      # 默认是 never
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

